### ISSUE TITLE
Intro to Arrays

### ISSUE THREAD

**Issue by siddhi-244** [HackClubRAIT/Wizard-Of-Docs#1]
### Description 
Inside arrays folder create a doc named `Intro_to_Arrays.md`.
Add syntax to declare an array in your preferred languages. Add examples as well.

### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

Hacktoberfest 
<hr/>

**Comment by mayankkaushik187** [comment]
Would love to get assigned to this task @siddhi-244

**Comment by siddhi-244** [comment]
Sure. Please take care of the folder structure. Happy contributing !🎊🎊🎊🎊🎊

**Comment by Swapna804** [comment]
I am participating in hacktoberfest and new to open source. Can you assign any issue please

**Comment by siddhi-244** [comment]
> I am participating in hacktoberfest and new to open source. Can you assign any issue please

It's already assigned.  You can create a new issue.
