### ISSUE TITLE
Hashing in data structures

### ISSUE THREAD

**Issue by purva2906** [HackClubRAIT/Wizard-Of-Docs#108]
### Description 
Information about Hashing in data structures.

### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

Hacktoberfest
<hr/>

**Comment by siddhi-244** [comment]
Go for it !

**Comment by purva2906** [comment]
[Hashing.md](https://github.com/HackClubRAIT/Wizard-Of-Docs/files/7446934/Hashing.md)
