### ISSUE TITLE
2 SUM problem

### ISSUE THREAD

**Issue by utkarsh006** [HackClubRAIT/Wizard-Of-Docs#115]
### Description 
2 Sum problem in arrays

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
Hackclub Rait

<hr/>

**Comment by Chaitalishetty** [comment]
@utkarsh006 Assigning this issue to you. Happy Coding!

**Comment by Chaitalishetty** [comment]
@utkarsh006 are you still working on this issue?

**Comment by pooja-sanap-53** [comment]
Can you assign this issue to me ? I can complete by today itself.

**Comment by Chaitalishetty** [comment]
@Ijaiswalshivam Assigning this issue to you. Happy Coding !
