### ISSUE TITLE
Insertion in singly linked list

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [HackClubRAIT/Wizard-Of-Docs#116]
### Description 
Insertion at the beginning, middle and end of the singly linked list.

### Programming language
- [ ] C
- [*] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
HackClubRAIT
<hr/>

**Comment by Chaitalishetty** [comment]
@Soumya-Kushwaha Assigning this issue to you. Happy Coding!
