### ISSUE TITLE
Segmented Sieve Algorithm

### ISSUE THREAD

**Issue by sid-am-ahd935** [HackClubRAIT/Wizard-Of-Docs#118]
### Description 
I want to add a document about the implementation of Segmented Sieve Algorithm, which uses Dynamic Programming for finding Prime Numbers upto a certain range in the most efficient way possible.

### Programming language
- C++
- Python

#### Are you contributing under any open-source program ?
I am contributing this under HACKCLUB RAIT Summer of Code.

<hr/>

**Comment by sid-am-ahd935** [comment]
Hi @Chaitalishetty can I implement this algorithm in both C++ and Python??
And one more question, if implementing i both languages, will it count as one or two issues?

**Comment by Chaitalishetty** [comment]
@sid-am-ahd935 Yeah sure go ahead! And if you're implementing both languages it will be considered as one issue.

**Comment by sid-am-ahd935** [comment]
So can you assign this issue to me?
