### ISSUE TITLE
Documentation for Quick Sort Algorithm

### ISSUE THREAD

**Issue by SUSHANT731** [HackClubRAIT/Wizard-Of-Docs#12]
### Description 
Describe more about the issue.
Code to sort an array using Quick Sort Algorithm(C++).
### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

HactoberFest
<hr/>

**Comment by SUSHANT731** [comment]
Could you please assign this issue to me.Thanks

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.

**Comment by SUSHANT731** [comment]
ok

**Comment by SUSHANT731** [comment]
@siddhi-244 this issue was assign to me how someones else pr is accepted??

**Comment by siddhi-244** [comment]
I am so sorry that was my fault. You can improve that document and add code in other languages

**Comment by SUSHANT731** [comment]
ok np I will add the code for c++ and will try to improve it!!
