### ISSUE TITLE
Changing the Checklist in PullRequest.md file 

### ISSUE THREAD

**Issue by GundaSudarrshan** [HackClubRAIT/Wizard-Of-Docs#120]
### Description of  the change
**Update needed for PullRequest.md** file in regards with HSOC

![image](https://user-images.githubusercontent.com/70209862/179364187-f9817f0c-f360-4662-b0ed-177922c83d54.png)

Should Change that **Above highlighted checklist** to **HSOC-22**

#### Are you contributing under any open-source program ?

HSOC-22 ( Hack-Club-Rait Summer Of Code 22)
<hr/>

**Comment by GundaSudarrshan** [comment]
@Chaitalishetty  You can Assign me this Issue.

**Comment by Chaitalishetty** [comment]
@GundaSudarrshan Assigning you this issue. Happy Coding!
