### ISSUE TITLE
Add documentation for stack

### ISSUE THREAD

**Issue by ashmeet-chhabra** [HackClubRAIT/Wizard-Of-Docs#121]
### Description 
I'll be updating the current empty stack readme. It'll comprise of:
- Introduction
- Implementation (using both array and linked list) 
- Basic operations

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
HSOC22

<hr/>

**Comment by Chaitalishetty** [comment]
@ashmeet-chhabra Assigning you this issue. Happy coding!
