### ISSUE TITLE
Add Sieve of Eratosthenes Algorithm inside the Docs

### ISSUE THREAD

**Issue by sid-am-ahd935** [HackClubRAIT/Wizard-Of-Docs#127]
### Description 
Hi I want to add the program Sieve Of Eratosthenes as a contribution for HSoC. This program is used for finding prime numbers upto a given limit. This is a hand-in-hand algorithm for the Segmented Sieve.

### Programming language
- [x] C++
- [x] Python

#### Are you contributing under any open-source program ?
HackClub RAIT Summer of Code

<hr/>

**Comment by PriyanshuGarg26** [comment]
Can you assign this issue to me . I want to contribute on this issue.

**Comment by Chaitalishetty** [comment]
@sid-am-ahd935 Assigning this issue to you. Happy Coding!
