### ISSUE TITLE
Add Array Problems

### ISSUE THREAD

**Issue by PriyanshuGarg26** [HackClubRAIT/Wizard-Of-Docs#129]
### Description 
Want to add Array Problems.
1.[Two Sum II](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/)
2.[3Sum](https://leetcode.com/problems/3sum/)
3.[Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements/)
### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [ .] Python

#### Are you contributing under any open-source program ?

HackClub RAIT
<hr/>

**Comment by Chaitalishetty** [comment]
@PriyanshuGarg26 Assigning you this issue. Happy Coding !
