### ISSUE TITLE
Add shell and radix sorting algorithms

### ISSUE THREAD

**Issue by vickyrules** [HackClubRAIT/Wizard-Of-Docs#130]
### Description 
want to add shell and radix sorting algorithms using cpp language

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

<hr/>

**Comment by vickyrules** [comment]
@Chaitalishetty  assign this issue to me, please.

**Comment by Chaitalishetty** [comment]
@vickyrules Assigning you this issue. Happy Coding !
