### ISSUE TITLE
Views of Binary Tree

### ISSUE THREAD

**Issue by ashmeet-chhabra** [HackClubRAIT/Wizard-Of-Docs#139]
### Description 
I'll add the implementations of different views of a binary tree, including
- left view
- right view
- top view
- bottom view

And brief about the intuition, and approach/traversal used

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

Hack Club RAIT (HSOC22)

<hr/>

**Comment by Chaitalishetty** [comment]
@ashmeet-chhabra Assigning you this issue. Happy Coding!

**Comment by saiprabhath2002** [comment]
Hello how exactly can I contribute to this one I am new to open source can you guide me please
