### ISSUE TITLE
Reverse a Linked List

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [HackClubRAIT/Wizard-Of-Docs#140]
### Description 
A complete doc about reversing a linked list using cpp
### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
HackClubRAIT

<hr/>

**Comment by Soumya-Kushwaha** [comment]
Please assign me @Chaitalishetty

**Comment by Chaitalishetty** [comment]
@Soumya-Kushwaha Assigning you this issue. Happy Coding!

**Comment by vedsom** [comment]
@Chaitalishetty  can you assign me this issue??
