### ISSUE TITLE
Add Linear Search and Binary Search Algorithm

### ISSUE THREAD

**Issue by tanya-gupta25** [HackClubRAIT/Wizard-Of-Docs#143]
### Description 
Will add linear search & binary search algorithm and code

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
HSOC

<hr/>

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by Chaitalishetty** [comment]
@tanya-gupta25 Assigning you this issue. Happy Coding!
