### ISSUE TITLE
Insertion sort algorithm and code

### ISSUE THREAD

**Issue by Koustavjr** [HackClubRAIT/Wizard-Of-Docs#144]
### Description 
Describe more about the issue.

### Programming language
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

#### Are you contributing under any open-source program ?

HSOC'22
<hr/>

**Comment by Koustavjr** [comment]
@Chaitalishetty can I contribute to this project under HSOC'22

**Comment by Chaitalishetty** [comment]
@Koustavjr Assigning you this issue. Happy Coding!
