### ISSUE TITLE
Akra_Bazi theorem

### ISSUE THREAD

**Issue by Koustavjr** [HackClubRAIT/Wizard-Of-Docs#153]
### Description 
A method to find time complexity in recursion problems.

### Programming language
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

#### Are you contributing under any open-source program ?

HSOC'22

<hr/>

**Comment by Koustavjr** [comment]
@Chaitalishetty can u please assign me this issue under HSOC'22?

**Comment by Chaitalishetty** [comment]
@Koustavjr Assigning you this issue. Happy Coding!

**Comment by Koustavjr** [comment]
@Chaitalishetty  can u please review my pr
