### ISSUE TITLE
Product of Array Except Self.cpp #16

### ISSUE THREAD

**Issue by rohith1125** [HackClubRAIT/Wizard-Of-Docs#17]
### Description 
Describe more about the issue.
This issue is regarding the PR [Product of Array Except Self.cpp #16](https://github.com/HackClubRAIT/Wizard-Of-Docs/pull/16)
### Programming language
- [ ] C
- [x] C++
- [x] Java
- [ ] Python

#### Are you contributing under any open-source program ?

hacktoberfest
<hr/>

**Comment by Red-0111** [comment]
Hi I would like to take this issue :D

**Comment by siddhi-244** [comment]
> Hi I would like to take this issue :D

You can open new issues

**Comment by siddhi-244** [comment]
> ### Description
> Describe more about the issue. This issue is regarding the PR [Product of Array Except Self.cpp #16](https://github.com/HackClubRAIT/Wizard-Of-Docs/pull/16)
> 
> ### Programming language
> * [ ]  C
> * [x]  C++
> * [ ]  Java
> * [ ]  Python
> 
> #### Are you contributing under any open-source program ?
> hacktoberfest

First try to create a issue get it assigned and then make a pr. This is a documentation project assigning this to you. Refer to merged prs.

**Comment by rohith1125** [comment]
@siddhi-244 I've created the pr before creating the issue, the pr has passed all the checks 🙂

**Comment by siddhi-244** [comment]
> @siddhi-244 I've created the pr before creating the issue, the pr has passed all the checks 🙂

Refer to merged prs. And you have to make issue first !!!!
