### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by siddhi-244** [HackClubRAIT/Wizard-Of-Docs#2]
### Description 
In algorithms folder inside Searching Algorithms folder create a file Linear_Search.md. Explain linear Search with examples as well as code in your preferred language.

### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

Hacktoberfest
<hr/>

**Comment by Asmit2952** [comment]
Can you assign this to me?

**Comment by siddhi-244** [comment]
> Can you assign this to me?

I will surely assign this issue to you tomorrow as Hacktoberfest will be starting from tomorrow!

**Comment by Asmit2952** [comment]
> > Can you assign this to me?
> 
> I will surely assign this issue to you tomorrow as Hacktoberfest will be starting from tomorrow!

Thank You and I would also suggest you to add `hacktoberfest` label, as it was clearly mentioned on their site.

**Comment by siddhi-244** [comment]
> > > Can you assign this to me?
> > 
> > 
> > I will surely assign this issue to you tomorrow as Hacktoberfest will be starting from tomorrow!
> 
> Thank You and I would also suggest you to add `hacktoberfest` label, as it was clearly mentioned on their site.

Already added .

**Comment by Asmit2952** [comment]
> > > > Can you assign this to me?
> > > 
> > > 
> > > I will surely assign this issue to you tomorrow as Hacktoberfest will be starting from tomorrow!
> > 
> > 
> > Thank You and I would also suggest you to add `hacktoberfest` label, as it was clearly mentioned on their site.
> 
> Already added .

Without number 21

**Comment by siddhi-244** [comment]
Happy contributing 🎊🎊🎊🎊

**Comment by prasanna16-12** [comment]
assigned me!

**Comment by siddhi-244** [comment]
> assigned me!

Sure if @Asmit2952 will not complete his pr within 5 days. It will be assigned to you.

**Comment by prasanna16-12** [comment]
so can i make my own issue and start working on it?

**Comment by siddhi-244** [comment]
> so can i make my own issue and start working on it?

Create another one. Don't create duplicate issues.

**Comment by prasanna16-12** [comment]
okk
