### ISSUE TITLE
Want to add Some Arrays files : )

### ISSUE THREAD

**Issue by kamleshjoshi8102** [HackClubRAIT/Wizard-Of-Docs#21]
### Description 

Hashing_with_arrays.cpp
Spiral Order Matrix.cpp
nextgreatorelement.cpp
union of two sorted arrays.cpp

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

hacktoberfest
<hr/>

**Comment by siddhi-244** [comment]
Hello @kamleshjoshi8102 make one issue for each array file. This is a documentation project so make sure to explain everything
