### ISSUE TITLE
Tree Traversal Inorder

### ISSUE THREAD

**Issue by prasanna16-12** [HackClubRAIT/Wizard-Of-Docs#29]
### Description 
Tree Traversal Inorder
### Programming language
- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

#### Are you contributing under any open-source program ?

hacktoberfest
<hr/>

**Comment by prasanna16-12** [comment]
assign me

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.
