### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by TD-17** [HackClubRAIT/Wizard-Of-Docs#30]
### Description 
Merge Sort is a Divide and Conquer algorithm.

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
hacktoberfest

<hr/>

**Comment by TD-17** [comment]
Could you please assign this issue to me?

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.

**Comment by TD-17** [comment]
Please review my PR @siddhi-244
