### ISSUE TITLE
Add Selection Sort Algorithm

### ISSUE THREAD

**Issue by neerajanand-coder** [HackClubRAIT/Wizard-Of-Docs#32]
**Description**

Hi! I want to add  Selection sort algorithm to this repo. The idea behind this algorithm is to sorts an array by repeatedly finding the minimum element (considering ascending order) from the unsorted part and putting it at the beginning.

**Programming language**
- [X] C
- [ ] C++
- [ ] Java
- [ ] Python

**Are you contributing under any open-source program?**
I am participating in Hacktoberfest 2021.

**Comment by neerajanand-coder** [comment]
Please assign this issue to me.

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.
