### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by mayur295** [HackClubRAIT/Wizard-Of-Docs#34]
### Description 
Creating Linkedlist.md file with detailed explanation in Data Structures folder

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?

<hr/>
hacktoberfest

**Comment by mayur295** [comment]
Please Assign Me

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.
