### ISSUE TITLE
Binary Search Algorithm in Java 

### ISSUE THREAD

**Issue by akankshaa02** [HackClubRAIT/Wizard-Of-Docs#38]
### Description 
Describe more about the issue.

### Programming language
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

#### Are you contributing under any open-source program ?

Hacktoberfest 
<hr/>

**Comment by siddhi-244** [comment]
There is a document already on binary search. Please add your code with example input and output in Java. Assigning this to you🎊🎊🎊🎊
