### ISSUE TITLE
Backtracking Documentation

### ISSUE THREAD

**Issue by hariketsheth** [HackClubRAIT/Wizard-Of-Docs#42]
### Description 
- Would like to contribute documentations for Backtracking

### Programming language

- [x] C++

#### Are you contributing under any open-source program ?
- Hacktoberfest

<hr/>

**Comment by nishajha629** [comment]
could you please assign this issue to me

**Comment by siddhi-244** [comment]
> ### Description
> * Would like to contribute documentations for Backtracking
> 
> ### Programming language
> * [x]  C++
> 
> #### Are you contributing under any open-source program ?
> * Hacktoberfest

Assigning this to you🎊🎊🎊

**Comment by siddhi-244** [comment]
> could you please assign this issue to me

Find other issues

**Comment by hariketsheth** [comment]
@siddhi-244 Actually, DSA Repositories are excluded from Hacktoberfest - according to the recent update. 
So @nishajha629 can take this up

**Comment by siddhi-244** [comment]
> @siddhi-244 Actually, DSA Repositories are excluded from Hacktoberfest - according to the recent update. So @nishajha629 can take this up

Who said that?

**Comment by hariketsheth** [comment]
> > @siddhi-244 Actually, DSA Repositories are excluded from Hacktoberfest - according to the recent update. So @nishajha629 can take this up
> 
> Who said that?

![image](https://user-images.githubusercontent.com/72455881/135703256-900a5045-d4d8-4689-b284-2f2ad3214c5f.png)
![image](https://user-images.githubusercontent.com/72455881/135703266-0c50a8c4-a376-4001-890e-10526fc3bc15.png)

**Comment by hariketsheth** [comment]
![image](https://user-images.githubusercontent.com/72455881/135703312-784fa0db-0eff-4a5e-8134-2e7293c0da24.png)

**Comment by siddhi-244** [comment]
@hariketsheth it's not our repository.  Our repository is a documentation repo. And it counts once ur prs are merged

**Comment by siddhi-244** [comment]
> > > @siddhi-244 Actually, DSA Repositories are excluded from Hacktoberfest - according to the recent update. So @nishajha629 can take this up
> > 
> > 
> > Who said that?
> 
> ![image](https://user-images.githubusercontent.com/72455881/135703256-900a5045-d4d8-4689-b284-2f2ad3214c5f.png) ![image](https://user-images.githubusercontent.com/72455881/135703266-0c50a8c4-a376-4001-890e-10526fc3bc15.png)

The prs need to be merged first.

**Comment by hariketsheth** [comment]
> @hariketsheth it's not our repository. Our repository is a documentation repo. And it counts once ur prs are merged

Ohh Right, This repository is not maintaining codes alone. 
Great ! Thank you for clarifying. :) 
Can you re-assign this issue to me. Also, sorry for the inconvinience
