### ISSUE TITLE
Bubble sort java

### ISSUE THREAD

**Issue by kindise** [HackClubRAIT/Wizard-Of-Docs#47]
### Description 
Hi. I want to add a program bubble sort in java

### Programming language
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

#### Are you contributing under any open-source program ?

<hr/>

**Comment by kindise** [comment]
Could you please assign this issue to me?

**Comment by harish127** [comment]
Hey, I can do this task.

**Comment by kindise** [comment]
> Hey, I can do this task.

Hmm you not create issue -_-
