### ISSUE TITLE
Stack data structure using array

### ISSUE THREAD

**Issue by strikerrocker** [HackClubRAIT/Wizard-Of-Docs#53]
### Description
Stack Data structure implemented using array.
### Programming language
- [x] C
- [ ] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
 hacktoberfest

<hr/>

**Comment by strikerrocker** [comment]
Done in #51

**Comment by siddhi-244** [comment]
Wait for issue to get assigned
