### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by IAmTamal** [HackClubRAIT/Wizard-Of-Docs#7]
### Description 
This is a code to sort an array with the help of insertion sort

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

#### Are you contributing under any open-source program ?
hacktoberfest

<hr/>

**Comment by IAmTamal** [comment]
Ma'am would you please assign me this Issue ?

**Comment by siddhi-244** [comment]
> ### Description
> This is a code to sort an array with the help of insertion sort
> 
> ### Programming language
> * [ ]  C
> * [x]  C++
> * [ ]  Java
> * [ ]  Python
> 
> #### Are you contributing under any open-source program ?
> hacktoberfest

Assigning this to you. Inside algorithms folder there is sorting algorithm folder inside that make a file Insertion_Sort.md and explain everything neatly.

**Comment by IAmTamal** [comment]
Maam along with the md file do i also add the code file ?

**Comment by TechSpiritSS** [comment]
I would like to contribute in this using C

**Comment by siddhi-244** [comment]
> I would like to contribute in this using C

Wait for this pr to be merged then you can go to improve a doc template and open a new issue for this.
